name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-images:
    runs-on: ubuntu-latest
    env: 
      BUILD_CONFIGURATION : debug
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag JTurpin/jimturpin.com::${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push JTurpin/jimturpin.com::${{steps.vars.outputs.tag}}
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag JTurpin/jimturpin.com::latest
      - name: Push the latest Docker image
        run: docker push JTurpin/jimturpin.com::latest
